blueprints/blueprint_utilities/blueprint_utilities.py
from dependencies import *

blueprint_utilities = Blueprint(
    "blueprint_utilities", __name__)


@blueprint_utilities.route("/")
def home():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    data["stats"] = [['100+', 'Subjects'],
                     ['100+', 'Skills'], ['1K+', 'Teachers']]
    responseTemplate["data"] = data
    print(responseTemplate)
    return render_template("home/home.htm", res=responseTemplate)


@blueprint_utilities.route("/careers")
def careers():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("careers/careers.htm", res=responseTemplate)


@blueprint_utilities.route("/contact-us")
def contact_us():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("contact-us/contact-us.htm", res=responseTemplate)


@blueprint_utilities.route("/help")
def help():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("help/help.htm", res=responseTemplate)

templates/utilities/404page/404page.htm
{% extends 'layout/layout.htm' %}

{% block title %}
Home
{% endblock %}

{% block stylesheets %}
<style>
    .image-404 {
        width: 25vw;
    }

    @media only screen and (max-width: 600px) {
        .image-404 {
            width: 50vw;
        }
    }
</style>
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col" style="text-align: center;">
            <div class="row">
                <div class="col">
                    <img src="{{ url_for('static', filename='images/image-404.png') }}" class="image-404">
                </div>
            </div>
            <h3 style="color: var(--color-accent);">
                <b>Looks like you hit a wall !!</b>
            </h3>
            <div style="margin-top: 24px;">
                <a href="{{ url_for('blueprint_utilities.home') }}"
                    style="border-radius: 100px;background-color: var(--color-accent);border:none;color : white; padding: 12px 24px;">GO
                    TO
                    HOMEPAGE</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}

{% endblock %}