blueprints/blueprint_sensei/blueprint_sensei.py
from dependencies import *
from models.dummy_models import dummySensei

blueprint_sensei = Blueprint('blueprint_sensei', __name__)


@blueprint_sensei.route('/sensei-all')
def sensei_all():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    data["countries"] = COUNTRIES
    responseTemplate["data"] = data
    return render_template('sensei-all/sensei-all.htm', res=responseTemplate)


@blueprint_sensei.route('/sensei/<username>')
def sensei_user(username):
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    data["countries"] = COUNTRIES
    data["sensei"] = dummySensei
    responseTemplate["data"] = data
    return render_template('sensei-profile/sensei-profile.htm', res=responseTemplate)

blueprints/blueprint_user/blueprint_user.py
from dependencies import *
from models.db_models import DBDetails, DBUser

blueprint_user = Blueprint('blueprint_user', __name__)


@blueprint_user.route("/login")
def login():
    if(current_user.is_authenticated):
        return redirect(url_for('blueprint_utilities.home'))
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("login/login.htm", res=responseTemplate)


@blueprint_user.route("/login", methods=['POST'])
def login_auth():
    data = request.json

    email = data["email"]
    password = data["password"]

    user = DBUser.query.filter_by(email=email).first()

    result = {
        "status": "",
        "message": ""
    }

    if not user or not check_password_hash(user.password, password):
        print('USERNAME or PASSWORD INCORRECT')
        result["status"] = "401"
        result["message"] = "Username or password is Incorrect"
        return jsonify(result)

    result["status"] = "200"
    result["message"] = "Authorization Successfull"

    login_user(user, remember=True)

    return jsonify(result)


@blueprint_user.route("/signup")
def signup():
    if(current_user.is_authenticated):
        return redirect(url_for('blueprint_utilities.home'))
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("signup/signup.htm", res=responseTemplate)


@blueprint_user.route("/signup", methods=['POST'])
def signup_auth():
    data = request.json

    email = data["email"]
    role = data["role"]
    password = data["password"]
    user_id = str(uuid.uuid4())

    user = DBUser.query.filter_by(email=data["email"]).first()

    result = {
        "status": "",
        "message": ""
    }

    if(user):
        print("User already exists")
        result["status"] = "401"
        result["message"] = "Email already registered"
        return jsonify(result)

    new_user = DBUser(user_id=user_id, email=email, role=role, password=generate_password_hash(
        password, method='sha256'))
    db.session.add(new_user)
    db.session.commit()

    result["status"] = "200"
    result["message"] = "Signup Successfull"
    return jsonify(result)


@blueprint_user.route("/settings")
@login_required
def settings():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["states"] = STATES
    data["countries"] = COUNTRIES
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("settings/settings.htm", res=responseTemplate)


@blueprint_user.route("/settings", methods=["POST"])
@login_required
def update_settings():
    result = {
        "status": "",
        "message": ""
    }

    if(current_user.is_authenticated() == False):
        result["status"] = "401"
        result["message"] = "Access denied"
        return jsonify(result)

    data = request.json

    name = data["name"]
    username = data["username"]
    email = data["email"]
    dob = data["dob"]
    pincode = data["pincode"]
    country = data["country"]
    state = data["state"]
    city = data["city"]
    address1 = data["address1"]
    address2 = data["address2"]
    address3 = data["address3"]
    landmark = data["landmark"]

    user_details = DBDetails.query.filter_by(email=current_user.email).first()

    result["status"] = "200"
    result["message"] = "Updated Successfully"
    return jsonify(result)


@blueprint_user.route("/profile")
@login_required
def profile():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("profile/profile.htm", res=responseTemplate)


@blueprint_user.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('blueprint_user.login'))


@blueprint_user.route("/notifications")
@login_required
def notifications():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("notifications/notifications.htm", res=responseTemplate)

blueprints/blueprint_utilities/blueprint_utilities.py
from dependencies import *

blueprint_utilities = Blueprint(
    "blueprint_utilities", __name__)


@blueprint_utilities.route("/")
def home():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    data["stats"] = [['100+', 'Subjects'],
                     ['100+', 'Skills'], ['1K+', 'Teachers']]
    responseTemplate["data"] = data
    print(responseTemplate)
    return render_template("home/home.htm", res=responseTemplate)


@blueprint_utilities.route("/careers")
def careers():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("careers/careers.htm", res=responseTemplate)


@blueprint_utilities.route("/contact-us")
def contact_us():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("contact-us/contact-us.htm", res=responseTemplate)


@blueprint_utilities.route("/help")
def help():
    responseTemplate["app-theme"] = request.cookies.get('app-theme')
    data = {

    }
    data["user"] = current_user
    responseTemplate["data"] = data
    return render_template("help/help.htm", res=responseTemplate)

templates/utilities/top-navigation/top-navigation-notification-container.htm
<div class="dropdown-menu notification-wrapper" aria-labelledby="navbarDropdownNotification">    
    <div class="row" style="padding: 12px;">
        <div class="col">
            {% for i in range(10) %}
            {{ notification_card() }}
            {% endfor %}
        </div>
    </div>
</div>

templates/utilities/top-navigation/top-navigation.htm
{% from "utilities/notification-card/notification-card.htm" import notification_card with context %}

<style>
    .notification-wrapper {
        width: 350px;
        position: absolute;
        border-radius: 8px;
        max-height: 50vh;
        overflow-y: auto;
        overflow-x: hidden;
    }

    .notification-card-hover {
        transition: all 0.2s ease-in-out;
    }

    .notification-card-hover:hover {
        box-shadow: 0 2px 4px var(--color-shadow);
    }
</style>

<div class="container-fluid custom-top-navigation">
    <div class="container">
        <nav class="custom-top-navigation" style="box-shadow: none;">
            <a class="custom-navbar-brand" href="{{ url_for('blueprint_utilities.home') }}">
                <img src="{{ url_for('static', filename='images/app-icon.png') }}" style="height: 38px;"> <span
                    id="top-navigation-app-name" style="color: var(--color-accent);">{{ res["app-name"] }}</span>
            </a>

            <span class="custom-navbar-menu-icon"><i class="bi bi-list" id="navigation-hamburger-icon"
                    onclick="toggleFullScreenMenu()"></i></span>

            <ul class="custom-navbar-content">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('blueprint_utilities.home') }}">Home</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('blueprint_sensei.sensei_all') }}">All Sensei</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('blueprint_utilities.careers') }}">Careers</a>
                </li>
            </ul>

            <ul class="custom-navbar-content" style="position: absolute;right:0;top:50%;transform: translateY(-50%);">
                {% if res["data"]["user"].is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownNotification" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="bi bi-bell-fill" style="color: var(--color-primary);cursor: pointer;"></i>
                    </a>
                    {% include 'utilities/top-navigation/top-navigation-notification-container.htm' %}
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownProfile" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {{ res["data"]["user"].email }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownProfile">
                        <div class="row" style="margin: 0 3px;">
                            <div class="col">
                                <table>
                                    <tbody>
                                        <tr>
                                            <td>
                                                <img src="{{ url_for('static', filename='images/sample-profile-image.webp') }}"
                                                    style="width: 48px;margin-right: 12px;">
                                            </td>
                                            <td>
                                                {{ res["data"]["user"].role }}
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <hr>
                            </div>
                        </div>
                        <a class="dropdown-item" href="{{ url_for('blueprint_user.profile') }}"><i
                                class="bi bi-person-rolodex"></i> Profile</a>
                        <a class="dropdown-item" href="{{ url_for('blueprint_user.settings') }}"><i
                                class="bi bi-gear-wide-connected"></i> Setting</a>
                        <a class="dropdown-item" href="{{ url_for('blueprint_utilities.help') }}"><i
                                class="bi bi-question-diamond"></i> Help</a>
                        <a class="dropdown-item" href="{{ url_for('blueprint_user.logout') }}"><i
                                class="bi bi-box-arrow-right"></i> Logout</a>
                    </div>
                </li>
                {% else %}
                <li class="nav-item active">
                    <a class="nav-link custom-btn-outline" href="{{ url_for('blueprint_user.login') }}">
                        Login</a>
                </li>
                <li class="nav-item active ml-2">
                    <a class="nav-link custom-btn-primary" style="color: var(--color-primary);"
                        href="{{ url_for('blueprint_user.signup') }}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
</div>

<script>
    function toggleFullScreenMenu() {
        if (document.getElementById("full-navigation-wrapper").style.left == "0px") {
            document.getElementById("full-navigation-wrapper").style.left = "-110%";
            document.querySelector("body").style.overflow = "auto";
        }
        else {
            document.getElementById("full-navigation-wrapper").style.left = "0px";
            document.querySelector("body").style.overflow = "hidden";
        }
    }   
</script>